/**
 * UX/SolidJS application runtime configuration bootstrap
 */

import { Config } from '@core/cfg/config.ts'
import { SolidProvider } from '@core/cfg/solid-provider.ts'

Config.init(new SolidProvider(), [
  'VITE_PACKAGE_APP_ID',
  'VITE_PACKAGE_TARGET',
  'VITE_PACKAGE_VERSION',
  'VITE_SUPABASE_EDGE_URL',
  'VITE_SUPABASE_RDBMS_URL',
  'VITE_SUPABASE_ANON_KEY',
  'VITE_SUPABASE_CLIENT_MODE',
  'VITE_SUPABASE_SERVICE_KEY',
  'VITE_JWT_SECRET',
  'VITE_LOCAL_DB_NAME'
], {
  'PACKAGE_APP_ID': 'VITE_PACKAGE_APP_ID',
  'PACKAGE_TARGET': 'VITE_PACKAGE_TARGET',
  'PACKAGE_VERSION': 'VITE_PACKAGE_VERSION',
  'SUPABASE_EDGE_URL': 'VITE_SUPABASE_EDGE_URL',
  'SUPABASE_RDBMS_URL': 'VITE_SUPABASE_RDBMS_URL',
  'SUPABASE_ANON_KEY': 'VITE_SUPABASE_ANON_KEY',
  'SUPABASE_CLIENT_MODE': 'VITE_SUPABASE_CLIENT_MODE',
  'SUPABASE_SERVICE_KEY': 'VITE_SUPABASE_SERVICE_KEY',
  'JWT_SECRET': 'VITE_JWT_SECRET',
  'LOCAL_DB_NAME': 'VITE_LOCAL_DB_NAME'
})

export { Config }
