/**
 * UX/SolidJS application runtime configuration bootstrap
 */

import { Config } from '@core/cfg/config.ts'
import { SolidProvider } from '@core/cfg/solid-provider.ts'

Config.init(new SolidProvider(), [
  'VITE_PACKAGE_APP_ID',
  'VITE_PACKAGE_TARGET',
  'VITE_PACKAGE_VERSION',
  'VITE_PRODUCT_NAME',
  'VITE_APPLICATION_NAME',
  'VITE_SUPABASE_EDGE_URL',
  'VITE_SUPABASE_RDBMS_URL',
  'VITE_SUPABASE_PUBLIC_KEY',
  'VITE_SUPABASE_CLIENT_MODE',
  'VITE_SERVICE_WORKER_ENABLED',
  'VITE_LOCAL_DB_NAME'
], {
  'PACKAGE_APP_ID': 'VITE_PACKAGE_APP_ID',
  'PACKAGE_TARGET': 'VITE_PACKAGE_TARGET',
  'PACKAGE_VERSION': 'VITE_PACKAGE_VERSION',
  'PRODUCT_NAME': 'VITE_PRODUCT_NAME',
  'APPLICATION_NAME': 'VITE_APPLICATION_NAME',
  'SUPABASE_EDGE_URL': 'VITE_SUPABASE_EDGE_URL',
  'SUPABASE_RDBMS_URL': 'VITE_SUPABASE_RDBMS_URL',
  'SUPABASE_PUBLIC_KEY': 'VITE_SUPABASE_PUBLIC_KEY',
  'SUPABASE_CLIENT_MODE': 'VITE_SUPABASE_CLIENT_MODE',
  'SERVICE_WORKER_ENABLED': 'VITE_SERVICE_WORKER_ENABLED',
  'LOCAL_DB_NAME': 'VITE_LOCAL_DB_NAME'
})

export { Config }
